#!/usr/bin/env ruby
# coding: utf-8

# GitHubユーザー名とリポジトリ名
print 'ユーザーネームを入力> '
USERNAME = gets.chomp.strip

print 'リポジトリ名を入力> '
REPO_NAME = gets.chomp.strip

# リモートリポジトリのSSH
REMOTE_REPO_URL = "git@github.com:#{USERNAME}/#{REPO_NAME}.git"

# 変更のステージング
system("git add .")

# コミット
system('git commit -m "Update file"')

# masterからmainに変更
system('git branch -M main')

# remoteリポジトリに接続してるかどうかの判定
existing_remote = system('git remote -v')

if existing_remote.nil?
  system("git remote add origin #{REMOTE_REPO_URL}")
  puts "リモートリポジトリを追加しました。"
else
  puts "リモートリポジトリはすでに存在しています。追加処理はスキップされました。"
end

# プッシュ()
system('git push -u origin main')
