#+OPTIONS: ^:{}
#+STARTUP: indent nolineimages overview num
#+TITLE: title
#+AUTHOR: HirotoSuzuki
#+EMAIL:     (concat "eyc69652@kwansei.ac.jp")
#+LANGUAGE:  jp
# +OPTIONS:   H:4 toc:t num:2
#+OPTIONS:   toc:nil
#+TAG: hoge, hoge2
#+TWITTER: off
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

M-x toggle-truncate-lines
* memo
** やり方
　- GitHubで作成したリポジトリのURLをコピーし、ローカルリポジトリと接続する
git remote add origin https://github.com/SuzukiHiroto08/practice.git

githubにpushする
git add .
git commit -m "Initial commit"
git push -u origin master
 nameとpassが求められる

スマホのgithub公式アプリの作成したリポジトリからorgファイルを閲覧することが出来た
** 改善点
 - hiroto_push.rb

[./hiroto_push ファイル名]コマンドでファイルをpushすることが出来たが、毎回Usernameとpasswordが求められる。
passwordは
Personal access tokens (classic)を入手、これ↓
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
これを無くしたい

→git config --global credential.helper store
git config --global user.name "SuzukiHiroto08"
git config --global user.email "your.email@example.com"

git remote set-url origin https://SuzukiHiroto08:YOUR_TOKEN@github.com/SuzukiHiroto08/practice.git
これでユーザー名、パスワードを求められなくなった。

コマンドの前に'./'を付ける必要がある。。。
今動かしているディレクトリ内でファイルを探してるから？
** ubuntu code
- Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

This message is shown once a day. To disable it please create the/home/hiroto/.hushlogin file.
hiroto@DESKTOP-8ELO98Q:~$ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
hiroto@DESKTOP-8ELO98Q ~> cd grad_research_23/senior/
hiroto@DESKTOP-8ELO98Q ~/g/senior (main)> ls
hiroto_help  hosoi  kazuki  kazuki_help  manato  nakata  suzuki
hiroto@DESKTOP-8ELO98Q ~/g/senior (main)> cd suzuki
hiroto@DESKTOP-8ELO98Q ~/g/s/suzuki (main)> ls
archives  layer_list  multiscale
hiroto@DESKTOP-8ELO98Q ~/g/s/suzuki (main)> mkdir practice
hiroto@DESKTOP-8ELO98Q ~/g/s/suzuki (main)> cd practice
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (main)> git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /home/hiroto/grad_research_23/senior/suzuki/practice/.git/
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ls
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> emacs README.org
fish: Job 1, 'emacs README.org' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ls
README.org
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> git remote add origin https://github.com/SuzukiHiroto08/practice.git
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> git add .
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> git commit -m "Initial commit"
[master (root-commit) ebf7db4] Initial commit
 1 file changed, 3 insertions(+)
 create mode 100644 README.org
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> git push -u origin masterUsername for 'https://github.com': SuzukiHiroto08
Password for 'https://SuzukiHiroto08@github.com':
remote: Support for password authentication was removed on August 13, 2021.remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/SuzukiHiroto08/practice.git/'
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [128]> git push -u origin
master
Username for 'https://github.com': SuzukiHiroto08
Password for 'https://SuzukiHiroto08@github.com': ⏎                        hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [SIGINT]> There are still jobs active:

   PID  Command
  8835  emacs README.org

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> git push -u origin masterUsername for 'https://github.com': SuzukiHiroto08
Password for 'https://SuzukiHiroto08@github.com':
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 233 bytes | 233.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/SuzukiHiroto08/practice.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> emacs hiroto_push.rb
fish: Job 2, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ls
README.org  hiroto_push.rb  hiroto_push.rb~
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> emacs README.org
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
fish: The file './hiroto_push.rb' is not executable by this user
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [126]> chmod +x hiroto_push.rb
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
./hiroto_push.rb: 5: require: not found
./hiroto_push.rb: 8: USERNAME: not found
./hiroto_push.rb: 9: REPO_NAME: not found
./hiroto_push.rb: 12: ORG_FILE_PATH: not found
./hiroto_push.rb: 15: unless: not found
./hiroto_push.rb: 16: puts: not found
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> emacs hiroto_push.rb
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> which ruby
/usr/bin/ruby
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> chmod +x hiroto_push.rb
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
./hiroto_push.rb:23:in `chdir': No such file or directory @ dir_s_chdir - /home/hiroto/org_files (Errno::ENOENT)
        from ./hiroto_push.rb:23:in `<main>'
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> pwd
/home/hiroto/grad_research_23/senior/suzuki/practice
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
/usr/lib/ruby/3.0.0/fileutils.rb:1596:in `block in fu_each_src_dest': same file: README.org and ./README.org (ArgumentError)
        from /usr/lib/ruby/3.0.0/fileutils.rb:1611:in `fu_each_src_dest0'
        from /usr/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from /usr/lib/ruby/3.0.0/fileutils.rb:432:in `cp'
        from ./hiroto_push.rb:26:in `<main>'
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
/usr/lib/ruby/3.0.0/fileutils.rb:1596:in `block in fu_each_src_dest': same file: README.org and README.org (ArgumentError)
        from /usr/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
        from /usr/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from /usr/lib/ruby/3.0.0/fileutils.rb:432:in `cp'
        from ./hiroto_push.rb:26:in `<main>'
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
/usr/lib/ruby/3.0.0/fileutils.rb:429:in `cp': unknown keyword: :force (ArgumentError)
        from ./hiroto_push.rb:26:in `<main>'
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
/usr/lib/ruby/3.0.0/fileutils.rb:1596:in `block in fu_each_src_dest': same file: README.org and README.org (ArgumentError)
        from /usr/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
        from /usr/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from /usr/lib/ruby/3.0.0/fileutils.rb:542:in `mv'
        from ./hiroto_push.rb:26:in `<main>'
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground



fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
/usr/lib/ruby/3.0.0/fileutils.rb:1596:in `block in fu_each_src_dest': same file: README.org and README.org (ArgumentError)
        from /usr/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
        from /usr/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from /usr/lib/ruby/3.0.0/fileutils.rb:432:in `cp'
        from ./hiroto_push.rb:26:in `<main>'
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
Error: README.org already exists. Please choose a different name or remove the existing file.
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
Error: README.org already exists. Please choose a different name or remove the existing file.
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
Error: README.org already exists. Please choose a different name or remove the existing file.
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
Error: README.org already exists. Please choose a different name or remove the existing file.
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb README.org
Error: README.org already exists. Please choose a different name or remove the existing file.
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> ls
README.org  hiroto_push.rb  hiroto_push.rb~
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> emacs hiroto.org
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb hiroto.org
Error: README.org already exists. Please choose a different name or remove the existing file.
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb hiroto.org
./hiroto_push.rb:23:in `chdir': No such file or directory @ dir_s_chdir - /home/hiroto/path/to/your/local/repo (Errno::ENOENT)
        from ./hiroto_push.rb:23:in `<main>'
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master) [1]> pwd
/home/hiroto/grad_research_23/senior/suzuki/practice
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> fg
Send job 3, 'emacs hiroto_push.rb' to foreground
fish: Job 3, 'emacs hiroto_push.rb' has stopped
hiroto@DESKTOP-8ELO98Q ~/g/s/s/practice (master)> ./hiroto_push.rb hiroto.org
[master d0ad3e6] Update file
 4 files changed, 82 insertions(+), 1 deletion(-)
 create mode 100644 hiroto.org
 create mode 100755 hiroto_push.rb
 create mode 100755 hiroto_push.rb~
error: remote origin already exists.
Username for 'https://github.com': fg
Password for 'https://fg@github.com': fish: Job 4, './hiroto_push.rb hiroto.org' has stopped
** Matz
 - ソフトウェアには物理的実体がないから名前が重要
　「適切に名前を付けることが出来る」と「その概念を理解している」は近い。プログラムの関数、変数もそう。

　
** gitで共有するメリット
 - gitの仕組みとしてファイルの変更履歴を記録したり、追跡することが出来る。
　共同作業を行う際、共有しているフォルダのコピーを自分のPCに作ることが出来る。
　gituhub公式アプリをスマートフォンからインストールすると、ファイルの内容をスマートフォンからでも閲覧できる。これにより、外出時などPCが手元にない状況でも、ファイルを閲覧できる。
　
